export default {
  GET_ALL: 'GET_ALL',
  GET_BY_CATEGORY: 'GET_BY_CATEGORY',
  SET_USER: 'SET_USER',
  ADD_CHAT: 'ADD_CHAT',
  SAVE_PROFILE: 'SAVE_PROFILE',
  REMOVE_SAVE: 'REMOVE_SAVE',
  MESSAGE_RECEIVED: 'MESSAGE_RECEIVED',
  MESSAGE_SENT: 'MESSAGE_SENT',
  SET_RECEIVER: 'SET_RECEIVER',
  DELETE_CHAT: 'DELETE_CHAT',
};
